### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by dlecan** [LedgerHQ/ledger-wallet-desktop#251]
Hello,

What is the license of this fantastic product ?

In [package.json](https://github.com/LedgerHQ/ledger-wallet-desktop/blob/master/package.json#L8), we can read "BSD-2-Clause".
But is it the one you have choosen ?

Anyway, an explicite LICENSE file would be great!

**Comment by meriadec** [comment]
Good catch @dlecan , now we got one :)
