### ISSUE TITLE
I need help with contact with Ledger Nano S

### ISSUE THREAD

**Issue by shoxive** [LedgerHQ/ledger-wallet-desktop#267]
I have cloned this project and build it succed,but it can't connect my Ledger device,
Can anyone give me some help?

**Comment by meriadec** [comment]
What do you mean by "can't connect"? Do you have any useful output in your terminal to share? Does the device appear in redux dev tools ?

Also note that the app is still in development, and you will not yet be able to use it for send/receive crypto.

**Comment by gre** [comment]
Hi @shoxive , i'm sorry but we are not providing support for now as this app is under heavy development. we are soon going to close the Issues section , it will be opened again when our first MVP gets released.
